version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3210:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
